config/routes.rb
Fooshbowl::Application.routes.draw do
  root to: "standings#index"
  resources :games
  resources :players
  resources :standings, only: [:index]
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :player1, class_name: "Player"
  belongs_to :player2, class_name: "Player"

  belongs_to :season

  default_scope { order(:created_at) }

  validates :season_id, presence: true

  before_validation :assign_season, if: -> { season_id.blank? }

  def goals_for(player)
    player1_id == player.id ? player1_score : player2_score
  end

  def goals_against(player)
    player1_id == player.id ? player2_score : player1_score
  end

  def win?(player)
    goals_for(player) > goals_against(player)
  end

  private

  def assign_season
    self.season = Season.current
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  def games
    Game.where(Game.arel_table[:player1_id].eq(id).or(Game.arel_table[:player2_id].eq(id)))
  end

  def games_played
      wins + losses
  end

  def wins
    games.select { |game| game.win?(self) }.size
  end

  def losses
    games.count - wins
  end

  def goals
    games.map { |game| game.goals_for(self) }.sum
  end

  def goals_against
    games.map { |game| game.goals_against(self) }.sum
  end

  def goal_diff
    goals - goals_against
  end

  def win_diff
    wins - losses
  end

  def winning_percentage
    return 0.0 if games.empty?
    (wins / games.size.to_f * 100).round(2)
  end
end

app/models/score_keeper.rb
class ScoreKeeper
  attr_accessor :player

  def initialize(player)
    @player = player
  end

  def goals
    player.games.map { |game| game.goals_for(player) }.sum
  end
end

app/models/season.rb
class Season < ActiveRecord::Base

  has_many :games

  def self.current
    Season.order('created_at desc').first
  end
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  has_many :games, class_name: 'TournamentGame'

  validates :name, presence: true

  def self.generate(name, n_rounds)
    self.transaction do
      tournament = Tournament.create(name: name)
      game = tournament.games.create!(round: n_rounds)
      generate_games(tournament, game, n_rounds - 1, n_rounds)
      tournament
    end
  end

  def self.generate_games(tournament, parent_game, round, n_rounds)
    return if round <= 0

    game1 = tournament.games.create!(round: round,
                                    parent_game: parent_game)

    game2 = tournament.games.create!(round: round,
                                    parent_game: parent_game)

    generate_games(tournament, game1, round-1, n_rounds)
    generate_games(tournament, game2, round-1, n_rounds)
  end

  # Create the Tournament with the correct number of games for the given
  # players.
  def self.create_with_players (players)
    self.transaction do
      tournament = Tournament.create(name: name)
      n_rounds = Math.log2(players.count).ceil
      games = []

      (players.count - 2).downto(0) do |game_no|
        round = n_rounds - Math.log2(players.count - game_no).ceil + 1
        parent_game = games[games.count / 2]
        games << tournament.games.create!(round: round, parent_game: parent_game)
      end
      tournament
    end
  end
end

app/models/tournament_game.rb
class TournamentGame < Game
  belongs_to :tournament

  belongs_to :parent_game, class_name: 'TournamentGame'

  validates :round, presence: true
  validates :tournament_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games   = Game.all
    @players = Player.all.sort_by(&:winning_percentage).reverse
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to games_path, notice: 'Game was successfully created.' }
        format.json { render action: 'index', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:player1_id, :player2_id, :player1_score, :player2_score)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render action: 'show', status: :created, location: @player }
      else
        format.html { render action: 'new' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name)
    end
end

app/controllers/standings_controller.rb
class StandingsController < ApplicationController

  # GET /players
  # GET /players.json
  def index
    @games   = Game.all
    @players = Player.all.sort_by(&:winning_percentage).reverse
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player1_id, "Player 1" %>
    <%= f.select :player1_id, Player.all.map { |p| [p.name, p.id] } %>
  </div>
  <div class="field">
    <%= f.label :player2_id, "Player 2" %>
    <%= f.select :player2_id, Player.all.map { |p| [p.name, p.id] } %>
  </div>
  <div class="field">
    <%= f.label :player1_score, "Player 1 Score" %>
    <%= f.number_field :player1_score %>
  </div>
  <div class="field">
    <%= f.label :player2_score, "Player 2 Score" %>
    <%= f.number_field :player2_score %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn" %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Player1:</strong>
  <%= @game.player1 %>
</p>

<p>
  <strong>Player2:</strong>
  <%= @game.player2 %>
</p>

<p>
  <strong>Player1 score:</strong>
  <%= @game.player1_score %>
</p>

<p>
  <strong>Player2 score:</strong>
  <%= @game.player2_score %>
</p>


<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fooshbowl</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="crest">
    <img src="/assets/crest.png" />
  </div>

  <div id="wrap">
    <%= yield %>
  </div>
</body>
</html>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Players</h1>

<table id ="stats">
    <tr class="headings">
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>


  <tbody>
    <% @players.each do |player| %>
    <tr>
      <td><%= player.name %></td>
      <td><%= link_to 'Show', player %></td>
      <td><%= link_to 'Edit', edit_player_path(player) %></td>
      <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'Add Player', new_player_path, class: "btn btn-medium table-button" %>
<%= link_to 'Show Standings', standings_path, class: "btn btn-medium table-button" %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>


<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/standings/index.html.erb
<h1>Standings</h1>

<table id="stats">
  <tr class="headings">
    <th>Name</th>
    <th>Games Played</th>
    <th>Wins</th>
    <th>Losses</th>
    <th>W%</th>
    <th>GD</th>
  </tr>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.games_played %></td>
        <td><%= player.wins %></td>
        <td><%= player.losses %></td>
        <td><%= player.winning_percentage %></td>
        <td><%= player.goal_diff %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'Add Game', new_game_path, class: "btn btn-medium table-button" %>
<%= link_to 'Show Players', players_path, class: "btn btn-medium table-button" %>